# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/release.yml on each tagged release.
# Source template: tools/homebrew/lore.formula.rb in AoJ/lore. Do not hand-edit
# in the tap — edit the template instead.

class LoreCli < Formula
  desc "Personal knowledge management tool (headless: lore, lore-serve, lore-worker)"
  homepage "https://github.com/AoJ/lore"
  version "1.0.8"
  license "MIT"

  # Public repo → plain release-asset URLs, no token/strategy needed.
  on_macos do
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "67f516bef89abaf9be9247a94248af195991d2517e6d60b859d00ad94e37491e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "cc1e4da23ff20c6d6081e12f3e20a689b7487c82969554130135de90ccf7fad7"
    end
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3333a282a87a650765e3cb9b2bc0c894fe0d2a115a6a5234103d1cea6be7db11"
    end
  end

  def install
    bin.install "lore", "lore-serve", "lore-worker"
  end

  def caveats
    <<~EOS
      The database defaults to:
        ~/Library/Application Support/lore/lore.db   (macOS)
        $XDG_DATA_HOME/lore/lore.db                  (Linux)
      Override the location with LORE_DB:
        export LORE_DB="$HOME/lore.db"

      The desktop GUI ships separately:  brew install --cask lore
    EOS
  end

  test do
    assert_match "lore", shell_output("#{bin}/lore --help 2>&1", 2)
  end
end
