# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/release.yml on each tagged release.
# Source template: tools/homebrew/lore.formula.rb in AoJ/lore. Do not hand-edit
# in the tap — edit the template instead.

class LoreCli < Formula
  desc "Personal knowledge management tool (headless: lore, lore-serve, lore-worker)"
  homepage "https://github.com/AoJ/lore"
  version "1.0.9"
  license "MIT"

  # Public repo → plain release-asset URLs, no token/strategy needed.
  on_macos do
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "cd41816074ace512cb64c6d7b01696099e957596f66491ceafed28b8e975034c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "259a475d957082775b1ac858a5a26b78354902f083f4809cc5cf9508f97ed36a"
    end
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "773111d47e5fba41681154de2758f6b87ebb2a3d3deebb77e09797bb9aaea6a7"
    end
  end

  def install
    bin.install "lore", "lore-serve", "lore-worker"
  end

  def caveats
    <<~EOS
      The database defaults to:
        ~/Library/Application Support/lore/lore.db   (macOS)
        $XDG_DATA_HOME/lore/lore.db                  (Linux)
      Override the location with LORE_DB:
        export LORE_DB="$HOME/lore.db"

      The desktop GUI ships separately:  brew install --cask lore
    EOS
  end

  test do
    assert_match "lore", shell_output("#{bin}/lore --help 2>&1", 2)
  end
end
